import { Fact } from '../data/facts';
import { Recipe } from '../data/recipes';

export const initialFacts: Fact[] = [
  {
    id: "language-movement",
    title: "Language Movement (1952)",
    description: "A historic movement to protect the Bangla language, shaping the nation’s identity.",
    details: `The Language Movement of 1952 is a turning point in the history of Bangladesh, where people sacrificed their lives to defend Bangla as their mother tongue.\n\nIt was a bold stand against the declaration that Urdu would be the sole state language, leading to widespread protests by students and citizens.\n\n🗣️ Why it matters\n\nThis movement laid the foundation for the nation's independence and established the right to cultural identity. Key moments include:\n\n✊ February 21 (Ekushey February) – The tragic day when protesters were killed.\n🏛️ Shaheed Minar – The monument built to honor the martyrs.\n🌐 International Mother Language Day – Recognized globally by UNESCO to celebrate linguistic diversity.\n\n❤️ The Legacy\n\nThe Language Movement is deeply emotional for every Bengali. It symbolizes the unbreakable bond we share with our language and honoring those who fought for freedom and dignity.`,
    category: "History",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPrAi2cC5SVf5Q2TwAxFSqk8vAOSREvVs7uw&s",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPrAi2cC5SVf5Q2TwAxFSqk8vAOSREvVs7uw&s",
      "https://socialchange.org.np/wp-content/uploads/2021/11/womens-protest-march-for-language-bangladesh-1952.jpg",
      "https://www.bssnews.net/assets/news_photos/2024/01/31/image-171077-1706705804.jpg",
      "https://bangladeshonrecord.com/Image/rare-images-of-the-language-movement/15_ekushey/",
      "https://en.samakal.com/uploads/2016/02/photos/sd_3466.jpg"
    ],
    imagePrompt: "Shaheed Minar Dhaka with flowers, people paying tribute on 21 February, emotional atmosphere.",
  },
  {
    id: "liberation-war",
    title: "Liberation War 1971",
    description: "The struggle that led to the independence of Bangladesh.",
    details: `The Liberation War of 1971 led to the creation of Bangladesh as an independent nation. It represents the courage, sacrifice, and determination of people who fought for freedom, dignity, and self-governance.\n\nFor nine months, millions of Bengalis from all walks of life united to resist oppression and fight for their fundamental rights.\n\n🔥 The Struggle and Triumph\n\nThe war was marked by significant sacrifices and decisive moments:\n\n📢 March 26 – The declaration of independence.\n🛡️ Mukti Bahini – The brave freedom fighters who led the resistance.\n✌️ December 16 (Victory Day) – The day Bangladesh finally achieved its freedom.\n\n🌍 Global Significance\n\nThe birth of Bangladesh is a testament to the power of the human spirit and the fight against injustice, inspiring freedom-loving people around the world.\n\n❤️ Why it matters\n\nThe Liberation War is the proudest chapter in the history of Bangladesh. Remembering 1971 unites the nation and reminds future generations of the price paid for the right to live freely and speak fiercely.`,
    category: "History",
    image: "https://www.liberationwarmuseumbd.org/public/images/390695.jpg",
    images: [
      "https://www.liberationwarmuseumbd.org/public/images/390695.jpg",
      "https://www.shutterstock.com/image-photo/dhaka-bangladesh-february-9th2024photographs-freedom-600nw-2425646685.jpg",
      "https://dscdn.daily-sun.com/english/uploads/news_photos/2019/12/16/Daily-sun-2019-12-16-39.jpg",
      "https://www.tbsnews.net/sites/default/files/styles/big_3/public/images/2021/10/19/rim1971024w00023-17-bangladesh.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQokaXNPwda3lpbu_5IjD0BA2-H-5BJPhkXcA&s",
    ],
    imagePrompt: "Victory Day Bangladesh, National Martyrs Memorial Savar, flags and crowd.",
  },
  {
    id: "pohela-boishakh",
    title: "Pohela Boishakh",
    description: "The Bengali New Year, celebrated with joy, colors, and unity.",
    details: `Pohela Boishakh marks the beginning of the Bengali New Year and represents renewal, hope, and unity. People celebrate with traditional dress, music, fairs, and food, embracing cultural identity beyond all differences.\n\nThis day is a spectacular showcase of Bengali culture, marking a fresh start for families and businesses alike.\n\n🎉 How it is Celebrated\n\nThe celebrations start at sunrise and continue throughout the day with:\n\n👗 Traditional Attire – Women wear red and white sarees, and men wear panjabis.\n🍽️ Festive Food – Eating Panta Bhaat (soaked rice) with Ilish (Hilsa fish) and Bhorta.\n🎶 Cultural Programs – Singing traditional songs like "Esho He Boishakh" by Rabindranath Tagore.\n🐅 Mangal Shobhajatra – The iconic, colorful procession wishing everyone well-being.\n\n🏙️ Community Spirit\n\nPohela Boishakh brings together people of all backgrounds, religions, and classes. The streets come alive with fairs (Boishakhi Mela) featuring local crafts, toys, and sweetmeats.`,
    category: "Culture",
    image: "https://d138zd1ktt9iqe.cloudfront.net/media/seo_landing_files/pohela-boishakh-1618228383.jpg",
    images: [
      "https://d138zd1ktt9iqe.cloudfront.net/media/seo_landing_files/pohela-boishakh-1618228383.jpg",
      "https://thefinancialexpress.com.bd/uploads/1681283626.jpg",
      "https://tbsnews.net/sites/default/files/styles/amp_metadata_content_image_min_696px_wide/public/images/2023/04/14/pohela_boishakh-01_1.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz-43v9h9JmZ-3f0iQz2PzR0V1v-9t7Z1o2w&s",
      "https://images.unsplash.com/photo-1617870952348-7524edfb61b7?w=800",
    ],
    imagePrompt: "Pohela Boishakh celebration Bangladesh, people in red and white traditional attire, colorful masks, joyful festival.",
  },
  {
    id: "mangal-shobhajatra",
    title: "Mangal Shobhajatra",
    description: "UNESCO Intangible Cultural Heritage—a vibrant New Year procession of hope and peace.",
    details: `Mangal Shobhajatra is an iconic colorful procession held on the morning of Pohela Boishakh. Organized by students and teachers of Dhaka University's Faculty of Fine Arts, it is recognized by UNESCO as Intangible Cultural Heritage.\n\nMassive motifs of birds, tigers, owls, and folk figures symbolize the triumph of light over darkness and universal peace.`,
    category: "Culture",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Mangal_Shobhajatra_1423_01.jpg",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/4/4e/Mangal_Shobhajatra_1423_01.jpg",
      "https://tbsnews.net/sites/default/files/styles/big_3/public/images/2022/04/14/mangal_shobhajatra-11.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH7fE7fI8jH9Wc2vF_8BwY1P4-8wZ3L4x1dQ&s"
    ],
    imagePrompt: "Dhaka University Mangal Shobhajatra procession with giant folk tiger and bird masks.",
  },
  {
    id: "baul-music",
    title: "Baul Music & Philosophy",
    description: "Mystic folk music of wandering minstrels, celebrated as UNESCO Intangible Cultural Heritage.",
    details: `The Bauls are mystic minstrels whose songs transcend orthodox religion, preaching humanism, soul searching, and divine love. Armed with the Ektara and Dotara, famous exponents like Lalon Shah created a profound philosophical movement recognized by UNESCO.`,
    category: "Art",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Baul_singer_at_Shantiniketan.jpg",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/4/4e/Baul_singer_at_Shantiniketan.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0VbY4D6pL9_L3T_uH3m9Z-L8Qz2X9qZ-8wA&s"
    ],
    imagePrompt: "Bengali Baul musician playing Ektara with saffron robes and joyful expression.",
  },
  {
    id: "bengali-hospitality",
    title: "Bengali Hospitality (Apyayan)",
    description: "The heartwarming tradition of welcoming guests with abundant home-cooked feasts and sweetmeats.",
    details: `In Bangladesh, hospitality ('Apyayan') is a core cultural value. Guests are considered blessings ('Mehman'), treated with warmth, endless refills of rice and delicacies, followed by paan (betel leaf) and tea.`,
    category: "Culture",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    images: ["https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800"],
    imagePrompt: "Traditional Bengali family dinner table laden with colorful bowls of fish curry, lentils, and sweets.",
  },
  {
    id: "pitha-festival",
    title: "Winter Pitha Utsab",
    description: "The seasonal tradition of baking sweet and savory rice cakes with fresh date palm jaggery.",
    details: `During the foggy winter months, Bangladesh comes alive with Pitha Utsab. Families make Bhapa, Chitoi, Patisapta, and Dudhpuli pithas using freshly harvested Aman rice and Khejur Gur (date molasses).`,
    category: "Culture",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Bhapa_Pitha.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/8/87/Bhapa_Pitha.jpg"],
    imagePrompt: "Steaming hot Bhapa Pitha on clay stove with date molasses filling, winter morning setting.",
  },
  {
    id: "jamdani",
    title: "Dhakai Jamdani",
    description: "UNESCO Heritage handwoven muslin with geometric and floral motifs.",
    details: `Jamdani is a legendary handloom woven textile of Bangladesh, recognized by UNESCO as Intangible Cultural Heritage of Humanity in 2013 and holding Geographical Indication (GI) status.`,
    category: "GI Product",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Jamdani_Saree.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/f/fe/Jamdani_Saree.jpg"],
    imagePrompt: "Intricate floral weave of Dhakai Jamdani saree on traditional handloom.",
  },
  {
    id: "dhakai-muslin",
    title: "Legendary Dhakai Muslin",
    description: "The gossamer fabric of royalty, revived through Bangladeshi scientific innovation.",
    details: `Once coveted by Roman emperors and Mughal courts, Dhakai Muslin was celebrated for its unbelievable fineness—a full saree could pass through a small ring. Bangladesh has recently revived this GI-certified treasure.`,
    category: "GI Product",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Muslin_dress.jpg/800px-Muslin_dress.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Muslin_dress.jpg/800px-Muslin_dress.jpg"],
    imagePrompt: "Ultra delicate sheer translucent Muslin fabric displayed elegantly.",
  },
  {
    id: "nakshi-kantha",
    title: "Nakshi Kantha",
    description: "Centuries-old embroidered folk quilts weaving personal stories and folklore.",
    details: `Nakshi Kantha is a century-old folk art of Bengal where discarded cotton fabrics are stitched together with colorful threads to create intricate narrative quilts with lotus, tree-of-life, and village scenes.`,
    category: "GI Product",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/52/Nakshi_Kantha_exhibit.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/5/52/Nakshi_Kantha_exhibit.jpg"],
    imagePrompt: "Close-up of elaborate red, blue, and yellow needlework on a vintage Nakshi Kantha quilt.",
  },
  {
    id: "rickshaw-art",
    title: "Dhaka Rickshaw & Rickshaw Art",
    description: "UNESCO recognized vibrant pop-art canvases rolling on the streets of Dhaka.",
    details: `Dhaka's cycle rickshaws and their back-panel paintings were inscribed on UNESCO's Intangible Cultural Heritage list in 2023. Bright movie stars, flowers, and rural landscapes turn city streets into moving galleries.`,
    category: "Art",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Rickshaw_Art_Dhaka.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/9/91/Rickshaw_Art_Dhaka.jpg"],
    imagePrompt: "Bright colorful hand-painted tin backboard of a Dhaka cycle rickshaw with floral motifs.",
  },
  {
    id: "land-of-rivers",
    title: "The Land of 700 Rivers",
    description: "The world's largest delta formed by the mighty Padma, Meghna, and Jamuna.",
    details: `Bangladesh is shaped by more than 700 rivers creating the fertile Bengal Delta. Life, transportation, and culture revolve around these waterways, from traditional boat racing (Nouka Baich) to riverine commerce.`,
    category: "Nature",
    image: "https://images.unsplash.com/photo-1578895210405-907db486c111?w=800",
    images: ["https://images.unsplash.com/photo-1578895210405-907db486c111?w=800"],
    imagePrompt: "Sunset over wide Bengali river with traditional wooden country boats and fishermen.",
  },
  {
    id: "sundarbans",
    title: "The Sundarbans Mangrove",
    description: "UNESCO World Heritage Site & home to the majestic Royal Bengal Tiger.",
    details: `The Sundarbans is the largest contiguous mangrove forest on Earth, located at the mouth of the Ganges and Brahmaputra rivers. It provides a sanctuary for the Royal Bengal Tiger, spotted deer, and saltwater crocodiles.`,
    category: "Nature",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Tiger_in_Sundarbans.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/e/ec/Tiger_in_Sundarbans.jpg"],
    imagePrompt: "Majestic Royal Bengal Tiger walking through lush green Sundarbans mangrove muddy waters.",
  },
  {
    id: "coxs-bazar",
    title: "Cox's Bazar Sea Beach",
    description: "The world's longest unbroken natural sandy sea beach spanning 120 kilometers.",
    details: `Stretching over 120 km along the Bay of Bengal, Cox's Bazar is renowned for its golden sands, towering cliffs in Himchari, and breathtaking ocean sunsets.`,
    category: "Nature",
    image: "https://images.unsplash.com/photo-1596405835955-e6111ef80503?w=800",
    images: ["https://images.unsplash.com/photo-1596405835955-e6111ef80503?w=800"],
    imagePrompt: "Endless golden sandy beach with crashing waves in Cox's Bazar under a pink and orange sunset.",
  },
  {
    id: "saint-martins",
    title: "Saint Martin's Island (Narikel Jinjira)",
    description: "The sole coral island of Bangladesh situated in the northeastern Bay of Bengal.",
    details: `Known locally as Coconut Island, Saint Martin's is a serene tropical paradise known for living coral reefs, azure blue waters, and fresh green coconut groves.`,
    category: "Nature",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800"],
    imagePrompt: "Crystal clear turquoise water hitting coral rocks and coconut trees on Saint Martin's Island.",
  },
  {
    id: "haor-region",
    title: "Tanguar Haor & Inland Seas",
    description: "Ramsar wetland sanctuary turning into a vast inland sea in monsoon.",
    details: `Tanguar Haor in Sunamganj is an ecologically critical wetland sanctuary. In monsoon, it transforms into an endless inland sea beneath the backdrop of the Meghalaya hills.`,
    category: "Nature",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800",
    images: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800"],
    imagePrompt: "Calm reflective waters of Tanguar Haor with traditional houseboat against blue mountain range.",
  },
  {
    id: "ilish",
    title: "Padma River Ilish (Hilsa)",
    description: "The undisputed National Fish of Bangladesh with GI certification and unmatched flavor.",
    details: `Ilish (Tenualosa ilisha) is a culinary obsession across Bengal. The silver fish migrating up the sweet waters of the Padma River develops an unrivaled rich buttery taste.`,
    category: "GI Product",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/BHilsa123.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/d/d3/BHilsa123.jpg"],
    imagePrompt: "Silver shimmering fresh Hilsa fish on ice at a riverside market in Chandpur.",
  },
  {
    id: "sakrain",
    title: "Old Dhaka Sakrain Kite Festival",
    description: "Winter sky illuminated with thousands of kites, fire breathers, and rooftop fireworks.",
    details: `Sakrain marks the transition of the sun into Capricorn in Old Dhaka. Rooftops come alive with competitive kite duels, traditional music, dragon fire-breathers, and night-time fireworks.`,
    category: "Culture",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800",
    images: ["https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800"],
    imagePrompt: "Old Dhaka skyline filled with hundreds of colorful flying kites during Sakrain festival.",
  },
  {
    id: "jatra",
    title: "Traditional Jatra Theatre",
    description: "Centuries-old musical folk drama performed on open-air village stages.",
    details: `Jatra is a vibrant form of folk theatre characterized by high drama, stylized music, and mythological or historical themes staged throughout rural Bengal during the winter dry season.`,
    category: "Art",
    image: "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?w=800",
    images: ["https://images.unsplash.com/photo-1469488865564-c2de10f69f96?w=800"],
    imagePrompt: "Dramatic live performance of actors in colorful historical costumes on open village Jatra stage.",
  },
  {
    id: "shataranji",
    title: "Rangpur Shataranji Carpets",
    description: "GI-certified traditional handloom woven rugs made with geometric motifs in Rangpur.",
    details: `Shataranji is a traditional decorative woven floor mat produced exclusively in Rangpur. Handcrafted on simple wooden frames using cotton threads, it holds official GI recognition.`,
    category: "GI Product",
    image: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800",
    images: ["https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800"],
    imagePrompt: "Geometric colorful pattern of authentic handmade Rangpur Shataranji carpet.",
  },
];

export const initialRecipes: Recipe[] = [
  {
    id: "chicken-tikiya",
    title: "Chicken Tikiya",
    description: "Savory minced chicken patties, a popular snack often served with Polao or as an afternoon treat.",
    category: "Popular Snacks",
    prepTime: "30 MIN",
    serves: "4 PERSONS",
    ingredients: [
      "500g minced chicken",
      "1 boiled potato (smashed)",
      "1 small onion (finely chopped)",
      "2 tbsp coriander leaves",
      "1 tsp ginger-garlic paste",
      "1–2 green chilies",
      "½ tsp turmeric",
      "1 tsp chili powder",
      "1 tsp garam masala",
      "Salt to taste",
      "2 tbsp breadcrumbs",
      "1 egg",
    ],
    instructions: [
      "Mix everything into a soft dough.",
      "Shape into small flat patties (bite-sized is best for events).",
      "Shallow fry on medium heat until golden brown on both sides.",
    ],
    image: "https://foodfoodonlyfood.wordpress.com/wp-content/uploads/2019/04/1-13.jpg",
    images: [
      "https://foodfoodonlyfood.wordpress.com/wp-content/uploads/2019/04/1-13.jpg",
      "https://i.ytimg.com/vi/4neXNNPyo4M/maxresdefault.jpg",
    ],
    imagePrompt: "Crispy golden brown Chicken Tikiya patties on a white plate.",
  },
  {
    id: "beef-tikiya",
    title: "Beef Tikiya",
    description: "Hearty minced beef patties with roasted cumin and spices, perfect for festive meals.",
    category: "Popular Snacks",
    prepTime: "30 MIN",
    serves: "4 PERSONS",
    ingredients: [
      "500g minced beef",
      "1 boiled potato (smashed)",
      "1 onion (finely chopped)",
      "1 tsp ginger-garlic paste",
      "1 tsp roasted cumin powder",
      "1 tsp chili powder",
      "½ tsp black pepper",
      "1 tsp garam masala",
      "Salt to taste",
      "2 tbsp breadcrumbs",
      "1 egg",
    ],
    instructions: [
      "Mix all ingredients well.",
      "Shape into patties.",
      "Fry until browned and fully cooked inside.",
    ],
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800",
    images: ["https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800"],
    imagePrompt: "Deliciously thick Beef Tikiya patties with salad.",
  },
  {
    id: "alur-chop",
    title: "Alur Chop (Potato Fritters)",
    description: "A beloved street food and Ramadan staple made of spiced mashed potatoes dipped in gram flour batter.",
    category: "Popular Snacks",
    prepTime: "25 MIN",
    serves: "4-5 PERSONS",
    ingredients: [
      "4–5 boiled potatoes (mashed)",
      "1 onion (finely chopped)",
      "1–2 green chilies",
      "½ tsp turmeric",
      "1 tsp chili powder",
      "Salt to taste",
      "Coriander leaves",
      "Gram flour (besan) for batter",
    ],
    instructions: [
      "Mix potato with spices, onion, chili, and coriander.",
      "Shape into oval-sized balls.",
      "Make a medium-thick batter with gram flour and water.",
      "Dip the potato balls and deep fry until golden and crispy.",
    ],
    image: "https://static.wixstatic.com/media/05c508_39d14807ef4d41fcbdb798c9ed74bb47~mv2.jpg/v1/fill/w_1000,h_1000,al_c,q_85,usm_0.66_1.00_0.01/05c508_39d14807ef4d41fcbdb798c9ed74bb47~mv2.jpg",
    images: ["https://static.wixstatic.com/media/05c508_39d14807ef4d41fcbdb798c9ed74bb47~mv2.jpg/v1/fill/w_1000,h_1000,al_c,q_85,usm_0.66_1.00_0.01/05c508_39d14807ef4d41fcbdb798c9ed74bb47~mv2.jpg"],
    imagePrompt: "Street-style Alur Chop crispy potato fritters.",
  },
  {
    id: "chapti",
    title: "Chapti (Savory Pancake)",
    description: "A local recipe from Bikrompur, traditionally enjoyed for breakfast or a light dinner.",
    category: "Popular Snacks",
    prepTime: "20 MIN",
    serves: "2-3 PERSONS",
    ingredients: [
      "1 cup rice flour",
      "1 egg",
      "1 small onion (chopped)",
      "Green chili",
      "Coriander leaves",
      "Salt to taste",
      "Water",
    ],
    instructions: [
      "Mix everything into a pourable batter.",
      "Heat a pan and lightly oil it.",
      "Pour a thin layer of batter like a pancake.",
      "Cook both sides until slightly crispy.",
    ],
    image: "https://i.ytimg.com/vi/UrW1pjsD91o/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCdQXshIkwgmDrjn4UeqliUtg9kyQ",
    images: ["https://i.ytimg.com/vi/UrW1pjsD91o/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCdQXshIkwgmDrjn4UeqliUtg9kyQ"],
    imagePrompt: "Traditional Chapti pancake on a cast iron pan.",
  },
  {
    id: "shorshe-ilish",
    title: "Shorshe Ilish (Mustard Hilsa)",
    description: "The crown jewel of Bengali cuisine—national fish Hilsa cooked in a pungent mustard gravy.",
    category: "Royal Meals",
    prepTime: "45 MIN",
    serves: "3-4 PERSONS",
    ingredients: [
      "4-6 pieces of Hilsa (Ilish) fish",
      "2 tbsp mustard seeds (ground to paste)",
      "3-4 green chilies (slitted)",
      "1 tsp turmeric powder",
      "1 tsp nigella seeds (kalo jeera)",
      "3-4 tbsp mustard oil (essential)",
      "Salt to taste",
    ],
    instructions: [
      "Marinate fish with salt and turmeric for 10 minutes.",
      "Heat mustard oil until smoking, then add nigella seeds.",
      "Briefly fry fish pieces on both sides.",
      "Add mustard paste, chilies, and a little warm water.",
      "Simmer covered until fish is tender and gravy is thick.",
    ],
    image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/%E0%A6%90%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A7%8D%E0%A6%AF%E0%A6%AC%E0%A6%BA%E0%A6%B9%E0%A7%80_%E0%A6%B8%E0%A6%B0%E0%A7%8D%E0%A6%B7%E0%A7%87_%E0%A6%87%E0%A6%B2%E0%A6%BF%E0%A6%B6.jpg",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/9/9a/%E0%A6%90%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A7%8D%E0%A6%AF%E0%A6%AC%E0%A6%BA%E0%A6%B9%E0%A7%80_%E0%A6%B8%E0%A6%B0%E0%A7%8D%E0%A6%B7%E0%A7%87_%E0%A6%87%E0%A6%B2%E0%A6%BF%E0%A6%B6.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/d/d3/BHilsa123.jpg",
    ],
    imagePrompt: "Classic Shorshe Ilish fish curry in thick yellow mustard gravy.",
  },
  {
    id: "kacchi-biryani",
    title: "Kacchi Biryani (Dhaka Style)",
    description: "Authentic Dhaka-style biryani where spiced raw mutton and rice are cooked together in sealed 'dum'.",
    category: "Royal Meals",
    prepTime: "90 MIN",
    serves: "6-8 PERSONS",
    ingredients: [
      "1 kg Mutton (large pieces)",
      "3 cups Basmati or Chinigura rice",
      "1/2 cup yogurt",
      "Ginger-garlic paste",
      "Special Biryani spice mix (cardamom, cinnamon, mace, nutmeg)",
      "Potatoes (fried golden with saffron color)",
      "Ghee and Fried onions (Bereshta)",
    ],
    instructions: [
      "Marinate mutton with yogurt, papaya paste, and spices for 2 hours.",
      "Layer raw meat at the bottom of a heavy pot, followed by fried potatoes.",
      "Add par-boiled rice (70% cooked) on top with saffron milk and ghee.",
      "Seal pot with flour dough and cook on low heat for 1 hour until meat is melt-in-mouth tender.",
    ],
    image: "https://dishstories.com/wp-content/uploads/2025/10/Kacchi-Biryani-in-Plate-with-mutton-piece.webp",
    images: [
      "https://dishstories.com/wp-content/uploads/2025/10/Kacchi-Biryani-in-Plate-with-mutton-piece.webp",
      "https://upload.wikimedia.org/wikipedia/commons/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg",
    ],
    imagePrompt: "Royal Kacchi Biryani served on a festive platter with tender mutton.",
  },
  {
    id: "fuchka",
    title: "Dhaka Fuchka",
    description: "The king of Bengali street foods—crispy fried hollow shells filled with spiced yellow peas and tangy tamarind water.",
    category: "Popular Snacks",
    prepTime: "30 MIN",
    serves: "3-4 PERSONS",
    ingredients: [
      "Crispy Fuchka shells",
      "Boiled yellow peas (Motor/Ghugni) & boiled potatoes",
      "Tangy Tok water (tamarind pulp, roasted cumin, black salt, chili)",
      "Chopped green chilies, coriander leaves, boiled egg grate",
    ],
    instructions: [
      "Prepare the mashed potato and spiced chickpea filling.",
      "Make the tamarind water with fresh green chili, lime juice, and roasted spices.",
      "Crack a hole in each fuchka shell, fill with potato-pea mixture, top with egg grate.",
      "Pour tangy tamarind water directly into the shell right before eating.",
    ],
    image: "https://images.deliveryhero.io/image/fd-bd/LH/f493-listing.jpg",
    images: [
      "https://images.deliveryhero.io/image/fd-bd/LH/f493-listing.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/e/e9/Pani_Puri1.JPG",
    ],
    imagePrompt: "Bengali roadside Fuchka stall with tangy tamarind water bowl and crispy shells.",
  },
  {
    id: "rasmalai",
    title: "Cumilla Rasmalai",
    description: "A legendary dessert from Cumilla consisting of mini cottage cheese patties soaked in thick, cardamom-infused malai.",
    category: "Sweet Treats",
    prepTime: "60 MIN",
    serves: "4-5 PERSONS",
    ingredients: [
      "Fresh Chhana (cottage cheese)",
      "1 liter full-fat milk reduced to thick malai",
      "Sugar syrup for boiling patties",
      "Saffron strands and green cardamom powder",
      "Pistachio slivers for garnish",
    ],
    instructions: [
      "Knead fresh chhana and shape into bite-sized balls or discs.",
      "Boil in light sugar syrup until puffed and spongy.",
      "Simmer milk with saffron and cardamom until reduced to a rich creamy consistency.",
      "Immerse the chhana patties into warm malai and chill thoroughly before serving.",
    ],
    image: "https://binnifood.com/wp-content/uploads/2023/12/%E0%A6%95%E0%A7%81%E0%A6%AE%E0%A6%BF%E0%A6%B2%E0%A7%8D%E0%A6%B2%E0%A6%BE%E0%A6%B0-%E0%A6%AC%E0%A6%BF%E0%A6%96%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%A4-%E0%A6%B0%E0%A6%B8%E0%A6%AE%E0%A6%BE%E0%A6%B2%E0%A6%BE%E0%A6%87-%E0%A6%A4%E0%A7%88%E0%A6%B0%E0%A6%BF%E0%A6%B0-%E0%A6%B0%E0%A7%87%E0%A6%B8%E0%A6%BF%E0%A6%AA%E0%A6%BF-%E0%A6%93-%E0%A6%87%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8.png",
    images: [
      "https://binnifood.com/wp-content/uploads/2023/12/%E0%A6%95%E0%A7%81%E0%A6%AE%E0%A6%BF%E0%A6%B2%E0%A7%8D%E0%A6%B2%E0%A6%BE%E0%A6%B0-%E0%A6%AC%E0%A6%BF%E0%A6%96%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%A4-%E0%A6%B0%E0%A6%B8%E0%A6%AE%E0%A6%BE%E0%A6%B2%E0%A6%BE%E0%A6%87-%E0%A6%A4%E0%A7%88%E0%A6%B0%E0%A6%BF%E0%A6%B0-%E0%A6%B0%E0%A7%87%E0%A6%B8%E0%A6%BF%E0%A6%AA%E0%A6%BF-%E0%A6%93-%E0%A6%87%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8.png",
      "https://upload.wikimedia.org/wikipedia/commons/a/ae/Ras_Malai_2.JPG",
    ],
    imagePrompt: "Cumilla authentic Rasmalai in a clay bowl with thick saffron-scented malai.",
  },
  {
    id: "bogura-doi",
    title: "Bogurar Mishti Doi (Sweet Yogurt)",
    description: "A GI certified iconic caramelized sweet yogurt baked and set in traditional porous earthenware pots in Bogura.",
    category: "Sweet Treats",
    prepTime: "480 MIN",
    serves: "4-6 PERSONS",
    ingredients: [
      "1 liter whole buffalo or cow milk",
      "1/2 cup caramelized sugar for deep amber color and caramel aroma",
      "2 tbsp authentic yogurt starter culture",
      "Unglazed porous clay pot (shora/matka)",
    ],
    instructions: [
      "Simmer milk until reduced to two-thirds volume.",
      "Add caramel syrup to get that distinctive reddish-brown hue.",
      "Allow milk to cool to lukewarm, gently whisk in starter culture.",
      "Pour into earthenware pot, wrap in blanket, and let ferment undisturbed in a warm spot for 8-10 hours.",
    ],
    image: "https://www.thedailystar.net/sites/default/files/styles/big_1/public/images/2024/08/12/_b3a6396.jpg",
    images: [
      "https://www.thedailystar.net/sites/default/files/styles/big_1/public/images/2024/08/12/_b3a6396.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/34/Mishti_Doi.jpg",
    ],
    imagePrompt: "Bogura sweet yogurt in clay pot, dense and glossy surface.",
  },
];
